services:
  hello-php:
    image: php:8.2
    working_dir: /usr/src/myapp
    environment:
      - PARAMETER=juquinha
    volumes:
      - .:/usr/src/myapp
    ports:
      - "8000:8000"
    command: "php -S 0.0.0.0:8000"
